# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("helloworld.proto", :syntax => :proto3) do
    add_message "simple.SimpleMessage" do
      optional :name, :string, 1
      optional :id, :string, 2
      optional :payload, :string, 3
    end
    add_message "simple.SimpleAck" do
      optional :message, :string, 1
      optional :originalId, :string, 2
      optional :respCode, :string, 3
    end
  end
end

module Simple
  SimpleMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("simple.SimpleMessage").msgclass
  SimpleAck = Google::Protobuf::DescriptorPool.generated_pool.lookup("simple.SimpleAck").msgclass
end
